[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
lib = { path = "../lib" }
hf-hub = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
reqwest = { workspace = true }
